name: First Workflow

on:
  push:
      branches:
      - main

jobs:
    example-job:
      runs-on: ubuntu-latest

      steps:
        - name: Print a message 
          run: echo "Workflow Work"


        - name: checkout repository
          uses: actions/checkout@v5.0.0

        - name: list repository files
          run: ls -la
